version: "0.1.0"
license: MIT (see LICENSE file for details)
homepage: https://modrinth.com/data-pack/arcane-core
source: https://github.com/rafalberezin/arcane-core
docs: https://rafalberezin.dev/projects/arcane-core
authors:
  - name: Rafał Berezin
    contact:
      discord: rafalberezin
      github: https://github.com/rafalberezin
      email: contact@rafalberezin.dev
